[project]
name = "speech-to-text-api-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-speech>=2.27.0",
    "pyaudio>=0.2.14",
]

[tool.uv.workspace]
members = ["help"]
